# python pandas tutorial-11

# File handling for replace function-dataferame.replace()

In [2]:
import pandas as pd

In [2]:
df=pd.read_csv('G:\\csv\\business-price-indexes-june-2020-quarter-corrections-to-previously-published-statistics.csv')
df

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1492
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1462,1465
6,FPIQ.SEB39,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1160
10,FPIQ.SEC31,2019.09,"Farm expenses price index, Dairy farms, Livest...",992,1074
11,FPIQ.SEC31,2019.12,"Farm expenses price index, Dairy farms, Livest...",1009,1091
12,FPIQ.SEC31,2020.03,"Farm expenses price index, Dairy farms, Livest...",984,1065
13,FPIQ.SEC39,2019.09,"Farm expenses price index, Dairy farms, Subtot...",1072,1079

In [3]:
df.replace(to_replace='FPIQ.SEB39',value="apple")

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1492
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1462,1465
6,apple,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194
7,apple,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200
8,apple,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1160
10,FPIQ.SEC31,2019.09,"Farm expenses price index, Dairy farms, Livest...",992,1074
11,FPIQ.SEC31,2019.12,"Farm expenses price index, Dairy farms, Livest...",1009,1091
12,FPIQ.SEC31,2020.03,"Farm expenses price index, Dairy farms, Livest...",984,1065
13,FPIQ.SEC39,2019.09,"Farm expenses price index, Dairy farms, Subtot...",1072,1079

In [3]:
df11=pd.read_csv('E:\csv files\SampleCSVfile.csv')
df11

,1,"Eldon Base for stackable storage shelf, platinum",Muhammed MacIntyre,3,-213.25,38.94,35,Nunavut,Storage & Organization,0.8
0,2,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Barry French,293,457.81,208.16,68.02,Nunavut,Appliances,0.58
1,3,"Cardinal Slant-D� Ring Binder, Heavy Gauge Vinyl",Barry French,293,46.71,8.69,2.99,Nunavut,Binders and Binder Accessories,0.39
2,4,R380,NaN,483,1198.97,195.99,3.99,Nunavut,Telephones and Communication,0.58
3,5,Holmes HEPA Air Purifier,Carlos Soltero,515,30.94,21.78,5.94,Nunavut,Appliances,0.50
4,6,G.E. Longer-Life Indoor Recessed Floodlight Bulbs,NaN,515,4.43,6.64,4.95,Nunavut,Office Furnishings,0.37
5,7,"Angle-D Binders with Locking Rings, Label Holders",Carl Jackson,613,NaN,7.30,7.72,NaN,Binders and Binder Accessories,0.38
6,8,"SAFCO Mobile Desk Side File, Wire Frame",Carl Jackson,613,127.70,42.76,6.22,Nunavut,Storage & Organization,NaN
7,9,"SAFCO Commercial Wire Shelving, Black",Monica Federle,643,NaN,138.14,35.00,Nunavut,Storage & Organization,NaN
8,10,Xerox 198,Dorothy Badders,678,-226.36,4.98,8.33,Nunavut,Paper,0.38

In [4]:
df11.replace('Carl Jackson','mango')

,1,"Eldon Base for stackable storage shelf, platinum",Muhammed MacIntyre,3,-213.25,38.94,35,Nunavut,Storage & Organization,0.8
0,2,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Barry French,293,457.81,208.16,68.02,Nunavut,Appliances,0.58
1,3,"Cardinal Slant-D� Ring Binder, Heavy Gauge Vinyl",Barry French,293,46.71,8.69,2.99,Nunavut,Binders and Binder Accessories,0.39
2,4,R380,NaN,483,1198.97,195.99,3.99,Nunavut,Telephones and Communication,0.58
3,5,Holmes HEPA Air Purifier,Carlos Soltero,515,30.94,21.78,5.94,Nunavut,Appliances,0.50
4,6,G.E. Longer-Life Indoor Recessed Floodlight Bulbs,NaN,515,4.43,6.64,4.95,Nunavut,Office Furnishings,0.37
5,7,"Angle-D Binders with Locking Rings, Label Holders",mango,613,NaN,7.30,7.72,NaN,Binders and Binder Accessories,0.38
6,8,"SAFCO Mobile Desk Side File, Wire Frame",mango,613,127.70,42.76,6.22,Nunavut,Storage & Organization,NaN
7,9,"SAFCO Commercial Wire Shelving, Black",Monica Federle,643,NaN,138.14,35.00,Nunavut,Storage & Organization,NaN
8,10,Xerox 198,Dorothy Badders,678,-226.36,4.98,8.33,Nunavut,Paper,0.38

In [5]:
df11.replace(0.58,200)

,1,"Eldon Base for stackable storage shelf, platinum",Muhammed MacIntyre,3,-213.25,38.94,35,Nunavut,Storage & Organization,0.8
0,2,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Barry French,293,457.81,208.16,68.02,Nunavut,Appliances,200.00
1,3,"Cardinal Slant-D� Ring Binder, Heavy Gauge Vinyl",Barry French,293,46.71,8.69,2.99,Nunavut,Binders and Binder Accessories,0.39
2,4,R380,NaN,483,1198.97,195.99,3.99,Nunavut,Telephones and Communication,200.00
3,5,Holmes HEPA Air Purifier,Carlos Soltero,515,30.94,21.78,5.94,Nunavut,Appliances,0.50
4,6,G.E. Longer-Life Indoor Recessed Floodlight Bulbs,NaN,515,4.43,6.64,4.95,Nunavut,Office Furnishings,0.37
5,7,"Angle-D Binders with Locking Rings, Label Holders",Carl Jackson,613,NaN,7.30,7.72,NaN,Binders and Binder Accessories,0.38
6,8,"SAFCO Mobile Desk Side File, Wire Frame",Carl Jackson,613,127.70,42.76,6.22,Nunavut,Storage & Organization,NaN
7,9,"SAFCO Commercial Wire Shelving, Black",Monica Federle,643,NaN,138.14,35.00,Nunavut,Storage & Organization,NaN
8,10,Xerox 198,Dorothy Badders,678,-226.36,4.98,8.33,Nunavut,Paper,0.38

In [4]:
df.replace('FPIQ.SEB39',"apple Orange")

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1492
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1462,1465
6,apple Orange,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194
7,apple Orange,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200
8,apple Orange,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1160
10,FPIQ.SEC31,2019.09,"Farm expenses price index, Dairy farms, Livest...",992,1074
11,FPIQ.SEC31,2019.12,"Farm expenses price index, Dairy farms, Livest...",1009,1091
12,FPIQ.SEC31,2020.03,"Farm expenses price index, Dairy farms, Livest...",984,1065
13,FPIQ.SEC39,2019.09,"Farm expenses price index, Dairy farms, Subtot...",1072,1079

In [5]:
df.replace(10,9)

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1492
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1462,1465
6,FPIQ.SEB39,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1160
10,FPIQ.SEC31,2019.09,"Farm expenses price index, Dairy farms, Livest...",992,1074
11,FPIQ.SEC31,2019.12,"Farm expenses price index, Dairy farms, Livest...",1009,1091
12,FPIQ.SEC31,2020.03,"Farm expenses price index, Dairy farms, Livest...",984,1065
13,FPIQ.SEC39,2019.09,"Farm expenses price index, Dairy farms, Subtot...",1072,1079

In [6]:
df.replace(1079,7999)

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1492
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1462,1465
6,FPIQ.SEB39,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1160
10,FPIQ.SEC31,2019.09,"Farm expenses price index, Dairy farms, Livest...",992,1074
11,FPIQ.SEC31,2019.12,"Farm expenses price index, Dairy farms, Livest...",1009,1091
12,FPIQ.SEC31,2020.03,"Farm expenses price index, Dairy farms, Livest...",984,1065
13,FPIQ.SEC39,2019.09,"Farm expenses price index, Dairy farms, Subtot...",1072,7999

In [7]:
df.replace([1434,1453,1412,1489,1507,1462],2)

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",2,2
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",2,1472
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",2,1431
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",2,1492
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",2,1510
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",2,1465
6,FPIQ.SEB39,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1160
10,FPIQ.SEC31,2019.09,"Farm expenses price index, Dairy farms, Livest...",992,1074
11,FPIQ.SEC31,2019.12,"Farm expenses price index, Dairy farms, Livest...",1009,1091
12,FPIQ.SEC31,2020.03,"Farm expenses price index, Dairy farms, Livest...",984,1065
13,FPIQ.SEC39,2019.09,"Farm expenses price index, Dairy farms, Subtot...",1072,1079

In [6]:
df11

,1,"Eldon Base for stackable storage shelf, platinum",Muhammed MacIntyre,3,-213.25,38.94,35,Nunavut,Storage & Organization,0.8
0,2,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Barry French,293,457.81,208.16,68.02,Nunavut,Appliances,0.58
1,3,"Cardinal Slant-D� Ring Binder, Heavy Gauge Vinyl",Barry French,293,46.71,8.69,2.99,Nunavut,Binders and Binder Accessories,0.39
2,4,R380,NaN,483,1198.97,195.99,3.99,Nunavut,Telephones and Communication,0.58
3,5,Holmes HEPA Air Purifier,Carlos Soltero,515,30.94,21.78,5.94,Nunavut,Appliances,0.50
4,6,G.E. Longer-Life Indoor Recessed Floodlight Bulbs,NaN,515,4.43,6.64,4.95,Nunavut,Office Furnishings,0.37
5,7,"Angle-D Binders with Locking Rings, Label Holders",Carl Jackson,613,NaN,7.30,7.72,NaN,Binders and Binder Accessories,0.38
6,8,"SAFCO Mobile Desk Side File, Wire Frame",Carl Jackson,613,127.70,42.76,6.22,Nunavut,Storage & Organization,NaN
7,9,"SAFCO Commercial Wire Shelving, Black",Monica Federle,643,NaN,138.14,35.00,Nunavut,Storage & Organization,NaN
8,10,Xerox 198,Dorothy Badders,678,-226.36,4.98,8.33,Nunavut,Paper,0.38

In [7]:
df11.replace(['Nunavut'],'yogi')

,1,"Eldon Base for stackable storage shelf, platinum",Muhammed MacIntyre,3,-213.25,38.94,35,Nunavut,Storage & Organization,0.8
0,2,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Barry French,293,457.81,208.16,68.02,yogi,Appliances,0.58
1,3,"Cardinal Slant-D� Ring Binder, Heavy Gauge Vinyl",Barry French,293,46.71,8.69,2.99,yogi,Binders and Binder Accessories,0.39
2,4,R380,NaN,483,1198.97,195.99,3.99,yogi,Telephones and Communication,0.58
3,5,Holmes HEPA Air Purifier,Carlos Soltero,515,30.94,21.78,5.94,yogi,Appliances,0.50
4,6,G.E. Longer-Life Indoor Recessed Floodlight Bulbs,NaN,515,4.43,6.64,4.95,yogi,Office Furnishings,0.37
5,7,"Angle-D Binders with Locking Rings, Label Holders",Carl Jackson,613,NaN,7.30,7.72,NaN,Binders and Binder Accessories,0.38
6,8,"SAFCO Mobile Desk Side File, Wire Frame",Carl Jackson,613,127.70,42.76,6.22,yogi,Storage & Organization,NaN
7,9,"SAFCO Commercial Wire Shelving, Black",Monica Federle,643,NaN,138.14,35.00,yogi,Storage & Organization,NaN
8,10,Xerox 198,Dorothy Badders,678,-226.36,4.98,8.33,yogi,Paper,0.38

In [12]:
df11.replace({'Muhammed MacIntyre':['Barry French','Carl Jackson']},'ramu')

,1,"Eldon Base for stackable storage shelf, platinum",Muhammed MacIntyre,3,-213.25,38.94,35,Nunavut,Storage & Organization,0.8
0,2,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",ramu,293,457.81,208.16,68.02,Nunavut,Appliances,0.58
1,3,"Cardinal Slant-D� Ring Binder, Heavy Gauge Vinyl",ramu,293,46.71,8.69,2.99,Nunavut,Binders and Binder Accessories,0.39
2,4,R380,NaN,483,1198.97,195.99,3.99,Nunavut,Telephones and Communication,0.58
3,5,Holmes HEPA Air Purifier,Carlos Soltero,515,30.94,21.78,5.94,Nunavut,Appliances,0.50
4,6,G.E. Longer-Life Indoor Recessed Floodlight Bulbs,NaN,515,4.43,6.64,4.95,Nunavut,Office Furnishings,0.37
5,7,"Angle-D Binders with Locking Rings, Label Holders",ramu,613,NaN,7.30,7.72,NaN,Binders and Binder Accessories,0.38
6,8,"SAFCO Mobile Desk Side File, Wire Frame",ramu,613,127.70,42.76,6.22,Nunavut,Storage & Organization,NaN
7,9,"SAFCO Commercial Wire Shelving, Black",Monica Federle,643,NaN,138.14,35.00,Nunavut,Storage & Organization,NaN
8,10,Xerox 198,Dorothy Badders,678,-226.36,4.98,8.33,Nunavut,Paper,0.38

In [15]:
df11.replace({'Muhammed MacIntyre':['Carl Jackson']},'syamu')

,1,"Eldon Base for stackable storage shelf, platinum",Muhammed MacIntyre,3,-213.25,38.94,35,Nunavut,Storage & Organization,0.8
0,2,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Barry French,293,457.81,208.16,68.02,Nunavut,Appliances,0.58
1,3,"Cardinal Slant-D� Ring Binder, Heavy Gauge Vinyl",Barry French,293,46.71,8.69,2.99,Nunavut,Binders and Binder Accessories,0.39
2,4,R380,NaN,483,1198.97,195.99,3.99,Nunavut,Telephones and Communication,0.58
3,5,Holmes HEPA Air Purifier,Carlos Soltero,515,30.94,21.78,5.94,Nunavut,Appliances,0.50
4,6,G.E. Longer-Life Indoor Recessed Floodlight Bulbs,NaN,515,4.43,6.64,4.95,Nunavut,Office Furnishings,0.37
5,7,"Angle-D Binders with Locking Rings, Label Holders",syamu,613,NaN,7.30,7.72,NaN,Binders and Binder Accessories,0.38
6,8,"SAFCO Mobile Desk Side File, Wire Frame",syamu,613,127.70,42.76,6.22,Nunavut,Storage & Organization,NaN
7,9,"SAFCO Commercial Wire Shelving, Black",Monica Federle,643,NaN,138.14,35.00,Nunavut,Storage & Organization,NaN
8,10,Xerox 198,Dorothy Badders,678,-226.36,4.98,8.33,Nunavut,Paper,0.38

In [8]:
df.replace([1434,1453,1412,1489,1507,1462],[1,2,3,500,1000,2000])

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1,2
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",2,1472
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",3,1431
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",500,1492
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1000,1510
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",2000,1465
6,FPIQ.SEB39,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1160
10,FPIQ.SEC31,2019.09,"Farm expenses price index, Dairy farms, Livest...",992,1074
11,FPIQ.SEC31,2019.12,"Farm expenses price index, Dairy farms, Livest...",1009,1091
12,FPIQ.SEC31,2020.03,"Farm expenses price index, Dairy farms, Livest...",984,1065
13,FPIQ.SEC39,2019.09,"Farm expenses price index, Dairy farms, Subtot...",1072,1079

In [11]:
df.replace({'Series reference':'FPIQ.SEA31'},'hows')

,Series reference,Period,Description,Revised,Initially published
0,hows,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453
1,hows,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472
2,hows,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1492
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1462,1465
6,FPIQ.SEB39,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1160
10,FPIQ.SEC31,2019.09,"Farm expenses price index, Dairy farms, Livest...",992,1074
11,FPIQ.SEC31,2019.12,"Farm expenses price index, Dairy farms, Livest...",1009,1091
12,FPIQ.SEC31,2020.03,"Farm expenses price index, Dairy farms, Livest...",984,1065
13,FPIQ.SEC39,2019.09,"Farm expenses price index, Dairy farms, Subtot...",1072,1079

In [14]:
df.replace({'Series reference':'FPIQ.SEA31','Revised':1412},'hows',)

,Series reference,Period,Description,Revised,Initially published
0,hows,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453
1,hows,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472
2,hows,2020.03,"Farm expenses price index, Horticulture and fr...",hows,1431
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1492
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1462,1465
6,FPIQ.SEB39,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1160
10,FPIQ.SEC31,2019.09,"Farm expenses price index, Dairy farms, Livest...",992,1074
11,FPIQ.SEC31,2019.12,"Farm expenses price index, Dairy farms, Livest...",1009,1091
12,FPIQ.SEC31,2020.03,"Farm expenses price index, Dairy farms, Livest...",984,1065
13,FPIQ.SEC39,2019.09,"Farm expenses price index, Dairy farms, Subtot...",1072,1079

In [16]:
df.replace('[A-Za_z]',0,regex=True)

    Series reference   Period  Description  Revised  Initially published
0                  0  2019.09            0     1434                 1453
1                  0  2019.12            0     1453                 1472
2                  0  2020.03            0     1412                 1431
3                  0  2019.09            0     1489                 1492
4                  0  2019.12            0     1507                 1510
5                  0  2020.03            0     1462                 1465
6                  0  2019.09            0     1193                 1194
7                  0  2019.12            0     1199                 1200
8                  0  2020.03            0     1187                 1188
9                  0  2019.12            0     1159                 1160
10                 0  2019.09            0      992                 1074
11                 0  2019.12            0     1009                 1091
12                 0  2020.03            0      984                 1065
13                 0  2019.09            0     1072                 1079

In [16]:
df11

,1,"Eldon Base for stackable storage shelf, platinum",Muhammed MacIntyre,3,-213.25,38.94,35,Nunavut,Storage & Organization,0.8
0,2,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Barry French,293,457.81,208.16,68.02,Nunavut,Appliances,0.58
1,3,"Cardinal Slant-D� Ring Binder, Heavy Gauge Vinyl",Barry French,293,46.71,8.69,2.99,Nunavut,Binders and Binder Accessories,0.39
2,4,R380,NaN,483,1198.97,195.99,3.99,Nunavut,Telephones and Communication,0.58
3,5,Holmes HEPA Air Purifier,Carlos Soltero,515,30.94,21.78,5.94,Nunavut,Appliances,0.50
4,6,G.E. Longer-Life Indoor Recessed Floodlight Bulbs,NaN,515,4.43,6.64,4.95,Nunavut,Office Furnishings,0.37
5,7,"Angle-D Binders with Locking Rings, Label Holders",Carl Jackson,613,NaN,7.30,7.72,NaN,Binders and Binder Accessories,0.38
6,8,"SAFCO Mobile Desk Side File, Wire Frame",Carl Jackson,613,127.70,42.76,6.22,Nunavut,Storage & Organization,NaN
7,9,"SAFCO Commercial Wire Shelving, Black",Monica Federle,643,NaN,138.14,35.00,Nunavut,Storage & Organization,NaN
8,10,Xerox 198,Dorothy Badders,678,-226.36,4.98,8.33,Nunavut,Paper,0.38

In [18]:
df11.replace('[A-Za-z]',0,regex=True)

,1,"Eldon Base for stackable storage shelf, platinum",Muhammed MacIntyre,3,-213.25,38.94,35,Nunavut,Storage & Organization,0.8
0,2,0,0.0,293,457.81,208.16,68.02,0.0,0,0.58
1,3,0,0.0,293,46.71,8.69,2.99,0.0,0,0.39
2,4,0,NaN,483,1198.97,195.99,3.99,0.0,0,0.58
3,5,0,0.0,515,30.94,21.78,5.94,0.0,0,0.50
4,6,0,NaN,515,4.43,6.64,4.95,0.0,0,0.37
5,7,0,0.0,613,NaN,7.30,7.72,NaN,0,0.38
6,8,0,0.0,613,127.70,42.76,6.22,0.0,0,NaN
7,9,0,0.0,643,NaN,138.14,35.00,0.0,0,NaN
8,10,0,0.0,678,-226.36,4.98,8.33,0.0,0,0.38

In [23]:
df11.replace({'Eldon Base for stackable storage shelf, platinum':'[A-Za-z]'},1000,regex=True)

,1,"Eldon Base for stackable storage shelf, platinum",Muhammed MacIntyre,3,-213.25,38.94,35,Nunavut,Storage & Organization,0.8
0,2,1000,Barry French,293,457.81,208.16,68.02,Nunavut,Appliances,0.58
1,3,1000,Barry French,293,46.71,8.69,2.99,Nunavut,Binders and Binder Accessories,0.39
2,4,1000,NaN,483,1198.97,195.99,3.99,Nunavut,Telephones and Communication,0.58
3,5,1000,Carlos Soltero,515,30.94,21.78,5.94,Nunavut,Appliances,0.50
4,6,1000,NaN,515,4.43,6.64,4.95,Nunavut,Office Furnishings,0.37
5,7,1000,Carl Jackson,613,NaN,7.30,7.72,NaN,Binders and Binder Accessories,0.38
6,8,1000,Carl Jackson,613,127.70,42.76,6.22,Nunavut,Storage & Organization,NaN
7,9,1000,Monica Federle,643,NaN,138.14,35.00,Nunavut,Storage & Organization,NaN
8,10,1000,Dorothy Badders,678,-226.36,4.98,8.33,Nunavut,Paper,0.38

In [17]:
df.replace({'Series reference':'[A-Za_z]'},0,regex=True)

,Series reference,Period,Description,Revised,Initially published
0,0,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453
1,0,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472
2,0,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431
3,0,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1492
4,0,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510
5,0,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1462,1465
6,0,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194
7,0,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200
8,0,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188
9,0,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1160
10,0,2019.09,"Farm expenses price index, Dairy farms, Livest...",992,1074
11,0,2019.12,"Farm expenses price index, Dairy farms, Livest...",1009,1091
12,0,2020.03,"Farm expenses price index, Dairy farms, Livest...",984,1065
13,0,2019.09,"Farm expenses price index, Dairy farms, Subtot...",1072,1079

In [18]:
df

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1492
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1462,1465
6,FPIQ.SEB39,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1160
10,FPIQ.SEC31,2019.09,"Farm expenses price index, Dairy farms, Livest...",992,1074
11,FPIQ.SEC31,2019.12,"Farm expenses price index, Dairy farms, Livest...",1009,1091
12,FPIQ.SEC31,2020.03,"Farm expenses price index, Dairy farms, Livest...",984,1065
13,FPIQ.SEC39,2019.09,"Farm expenses price index, Dairy farms, Subtot...",1072,1079

In [20]:
df.replace('FPIQ.SEC31', method='ffill')

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1492
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1462,1465
6,FPIQ.SEB39,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1160
10,FPIQ.SEB99,2019.09,"Farm expenses price index, Dairy farms, Livest...",992,1074
11,FPIQ.SEB99,2019.12,"Farm expenses price index, Dairy farms, Livest...",1009,1091
12,FPIQ.SEB99,2020.03,"Farm expenses price index, Dairy farms, Livest...",984,1065
13,FPIQ.SEC39,2019.09,"Farm expenses price index, Dairy farms, Subtot...",1072,1079

In [21]:
df.replace('FPIQ.SEC31', method='bfill')

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1492
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1462,1465
6,FPIQ.SEB39,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1160
10,FPIQ.SEC39,2019.09,"Farm expenses price index, Dairy farms, Livest...",992,1074
11,FPIQ.SEC39,2019.12,"Farm expenses price index, Dairy farms, Livest...",1009,1091
12,FPIQ.SEC39,2020.03,"Farm expenses price index, Dairy farms, Livest...",984,1065
13,FPIQ.SEC39,2019.09,"Farm expenses price index, Dairy farms, Subtot...",1072,1079

In [ ]:
df.replace(1434,1000, inplace= TR)