# python pandas tutorial-13

# pandas interpolate()

In [3]:
import pandas as pd

In [8]:
import pandas as pd
df=pd.read_csv('G:\\csv\\business-price-indexes-june-2020-missing value file.csv')
df

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453.0
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472.0
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431.0
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,NaN
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510.0
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",4500,1465.0
6,NaN,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194.0
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200.0
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188.0
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,NaN

In [5]:
df1=pd.read_csv('E:\csv files\ppppppppppppppppp.csv')
df1

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,9/1/2019,"Farm expenses price index, Horticulture and fr...",1434.0,1453.0
1,FPIQ.SEA31,10/2/2020,"Farm expenses price index, Horticulture and fr...",1453.0,1472.0
2,FPIQ.SEA31,11/3/2020,"Farm expenses price index, Horticulture and fr...",1412.0,1431.0
3,FPIQ.SEB31,12/4/2020,"Farm expenses price index, Sheep, beef, and gr...",1489.0,1492.0
4,FPIQ.SEB31,13/5/2020,NaN,1507.0,1510.0
5,NaN,14/6/2020,"Farm expenses price index, Sheep, beef, and gr...",NaN,1465.0
6,FPIQ.SEB39,15/7/2020,"Farm expenses price index, Sheep, beef, and gr...",1193.0,1194.0
7,FPIQ.SEB39,12/8/2020,NaN,1199.0,1200.0
8,FPIQ.SEB39,12/9/2020,"Farm expenses price index, Sheep, beef, and gr...",1187.0,NaN

In [8]:
df1.interpolate(limit=1)

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,9/1/2019,"Farm expenses price index, Horticulture and fr...",1434.0,1453.0
1,FPIQ.SEA31,10/2/2020,"Farm expenses price index, Horticulture and fr...",1453.0,1472.0
2,FPIQ.SEA31,11/3/2020,"Farm expenses price index, Horticulture and fr...",1412.0,1431.0
3,FPIQ.SEB31,12/4/2020,"Farm expenses price index, Sheep, beef, and gr...",1489.0,1492.0
4,FPIQ.SEB31,13/5/2020,NaN,1507.0,1510.0
5,NaN,14/6/2020,"Farm expenses price index, Sheep, beef, and gr...",1350.0,1465.0
6,FPIQ.SEB39,15/7/2020,"Farm expenses price index, Sheep, beef, and gr...",1193.0,1194.0
7,FPIQ.SEB39,12/8/2020,NaN,1199.0,1200.0
8,FPIQ.SEB39,12/9/2020,"Farm expenses price index, Sheep, beef, and gr...",1187.0,1200.0

In [9]:
df.interpolate(limit=1)

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453.0
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472.0
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431.0
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1470.5
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510.0
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",4500,1465.0
6,NaN,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194.0
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200.0
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188.0
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1188.0

In [10]:
df.interpolate(limit=2)

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453.0
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472.0
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431.0
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1470.5
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510.0
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",4500,1465.0
6,NaN,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194.0
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200.0
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188.0
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1188.0

In [12]:
df1

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,9/1/2019,"Farm expenses price index, Horticulture and fr...",1434.0,1453.0
1,FPIQ.SEA31,10/2/2020,"Farm expenses price index, Horticulture and fr...",1453.0,1472.0
2,FPIQ.SEA31,11/3/2020,"Farm expenses price index, Horticulture and fr...",1412.0,1431.0
3,FPIQ.SEB31,12/4/2020,"Farm expenses price index, Sheep, beef, and gr...",1489.0,1492.0
4,FPIQ.SEB31,13/5/2020,NaN,1507.0,1510.0
5,NaN,14/6/2020,"Farm expenses price index, Sheep, beef, and gr...",NaN,1465.0
6,FPIQ.SEB39,15/7/2020,"Farm expenses price index, Sheep, beef, and gr...",1193.0,1194.0
7,FPIQ.SEB39,12/8/2020,NaN,1199.0,1200.0
8,FPIQ.SEB39,12/9/2020,"Farm expenses price index, Sheep, beef, and gr...",1187.0,NaN

In [10]:
df1.interpolate(limit=1,limit_direction='forward')

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,9/1/2019,"Farm expenses price index, Horticulture and fr...",1434.0,1453.0
1,FPIQ.SEA31,10/2/2020,"Farm expenses price index, Horticulture and fr...",1453.0,1472.0
2,FPIQ.SEA31,11/3/2020,"Farm expenses price index, Horticulture and fr...",1412.0,1431.0
3,FPIQ.SEB31,12/4/2020,"Farm expenses price index, Sheep, beef, and gr...",1489.0,1492.0
4,FPIQ.SEB31,13/5/2020,NaN,1507.0,1510.0
5,NaN,14/6/2020,"Farm expenses price index, Sheep, beef, and gr...",1350.0,1465.0
6,FPIQ.SEB39,15/7/2020,"Farm expenses price index, Sheep, beef, and gr...",1193.0,1194.0
7,FPIQ.SEB39,12/8/2020,NaN,1199.0,1200.0
8,FPIQ.SEB39,12/9/2020,"Farm expenses price index, Sheep, beef, and gr...",1187.0,1200.0

In [13]:
df1.interpolate(limit=1,limit_direction='backward')

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,9/1/2019,"Farm expenses price index, Horticulture and fr...",1434.0,1453.0
1,FPIQ.SEA31,10/2/2020,"Farm expenses price index, Horticulture and fr...",1453.0,1472.0
2,FPIQ.SEA31,11/3/2020,"Farm expenses price index, Horticulture and fr...",1412.0,1431.0
3,FPIQ.SEB31,12/4/2020,"Farm expenses price index, Sheep, beef, and gr...",1489.0,1492.0
4,FPIQ.SEB31,13/5/2020,NaN,1507.0,1510.0
5,NaN,14/6/2020,"Farm expenses price index, Sheep, beef, and gr...",1350.0,1465.0
6,FPIQ.SEB39,15/7/2020,"Farm expenses price index, Sheep, beef, and gr...",1193.0,1194.0
7,FPIQ.SEB39,12/8/2020,NaN,1199.0,1200.0
8,FPIQ.SEB39,12/9/2020,"Farm expenses price index, Sheep, beef, and gr...",1187.0,NaN

In [13]:
df.interpolate(limit=1,limit_direction="backward")

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453.0
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472.0
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431.0
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1470.5
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510.0
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",4500,1465.0
6,NaN,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194.0
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200.0
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188.0
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,NaN

In [16]:
df1.interpolate(limit=1,limit_area='inside')

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,9/1/2019,"Farm expenses price index, Horticulture and fr...",1434.0,1453.0
1,FPIQ.SEA31,10/2/2020,"Farm expenses price index, Horticulture and fr...",1453.0,1472.0
2,FPIQ.SEA31,11/3/2020,"Farm expenses price index, Horticulture and fr...",1412.0,1431.0
3,FPIQ.SEB31,12/4/2020,"Farm expenses price index, Sheep, beef, and gr...",1489.0,1492.0
4,FPIQ.SEB31,13/5/2020,NaN,1507.0,1510.0
5,NaN,14/6/2020,"Farm expenses price index, Sheep, beef, and gr...",1350.0,1465.0
6,FPIQ.SEB39,15/7/2020,"Farm expenses price index, Sheep, beef, and gr...",1193.0,1194.0
7,FPIQ.SEB39,12/8/2020,NaN,1199.0,1200.0
8,FPIQ.SEB39,12/9/2020,"Farm expenses price index, Sheep, beef, and gr...",1187.0,NaN

In [14]:
df.interpolate(limit=1,limit_area="inside")

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453.0
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472.0
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431.0
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1470.5
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510.0
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",4500,1465.0
6,NaN,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194.0
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200.0
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188.0
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,NaN

In [15]:
df.interpolate(limit=4,limit_area="inside")

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453.0
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472.0
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431.0
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1470.5
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510.0
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",4500,1465.0
6,NaN,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194.0
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200.0
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188.0
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,NaN

In [16]:
df.interpolate(limit_area="inside")

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453.0
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472.0
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431.0
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1470.5
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510.0
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",4500,1465.0
6,NaN,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194.0
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200.0
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188.0
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,NaN

In [17]:
df1.interpolate(limit=1,limit_area='outside')

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,9/1/2019,"Farm expenses price index, Horticulture and fr...",1434.0,1453.0
1,FPIQ.SEA31,10/2/2020,"Farm expenses price index, Horticulture and fr...",1453.0,1472.0
2,FPIQ.SEA31,11/3/2020,"Farm expenses price index, Horticulture and fr...",1412.0,1431.0
3,FPIQ.SEB31,12/4/2020,"Farm expenses price index, Sheep, beef, and gr...",1489.0,1492.0
4,FPIQ.SEB31,13/5/2020,NaN,1507.0,1510.0
5,NaN,14/6/2020,"Farm expenses price index, Sheep, beef, and gr...",NaN,1465.0
6,FPIQ.SEB39,15/7/2020,"Farm expenses price index, Sheep, beef, and gr...",1193.0,1194.0
7,FPIQ.SEB39,12/8/2020,NaN,1199.0,1200.0
8,FPIQ.SEB39,12/9/2020,"Farm expenses price index, Sheep, beef, and gr...",1187.0,1200.0

In [17]:
df.interpolate(limit_area="outside")

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453.0
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472.0
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431.0
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,NaN
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510.0
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",4500,1465.0
6,NaN,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194.0
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200.0
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188.0
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1188.0

In [18]:
df

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453.0
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472.0
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431.0
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,NaN
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510.0
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",4500,1465.0
6,NaN,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194.0
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200.0
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188.0
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,NaN

In [19]:
df.interpolate(inplace=True)
df

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453.0
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472.0
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431.0
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1470.5
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510.0
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",4500,1465.0
6,NaN,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194.0
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200.0
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188.0
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1188.0

In [20]:
df

,Series reference,Period,Description,Revised,Initially published
0,FPIQ.SEA31,2019.09,"Farm expenses price index, Horticulture and fr...",1434,1453.0
1,FPIQ.SEA31,2019.12,"Farm expenses price index, Horticulture and fr...",1453,1472.0
2,FPIQ.SEA31,2020.03,"Farm expenses price index, Horticulture and fr...",1412,1431.0
3,FPIQ.SEB31,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1489,1470.5
4,FPIQ.SEB31,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1507,1510.0
5,FPIQ.SEB31,2020.03,"Farm expenses price index, Sheep, beef, and gr...",4500,1465.0
6,NaN,2019.09,"Farm expenses price index, Sheep, beef, and gr...",1193,1194.0
7,FPIQ.SEB39,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1199,1200.0
8,FPIQ.SEB39,2020.03,"Farm expenses price index, Sheep, beef, and gr...",1187,1188.0
9,FPIQ.SEB99,2019.12,"Farm expenses price index, Sheep, beef, and gr...",1159,1188.0